version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - sudo yum install gcc-c++
      - pip install -r requirements.txt
      # - python application.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - application.py
    - requirements.txt